# Generated by Django 4.2.3 on 2023-07-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_price_transactions_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdings',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
