# Generated by Django 4.2.3 on 2023-07-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_holdings_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
