# Generated by Django 4.2.3 on 2023-07-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='description',
        ),
    ]
