# Generated by Django 4.2.3 on 2023-07-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_lesson_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('order', 'classroom')},
        ),
    ]
