# Generated by Django 4.2.3 on 2023-08-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='long_description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='short_description',
            new_name='description',
        ),
    ]
