# Generated by Django 4.2.3 on 2023-08-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_rename_long_description_lesson_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploaded_images/'),
        ),
    ]
