# Generated by Django 4.2.3 on 2023-08-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_lesson_learning_objectives_alter_lesson_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='learning_objectives',
        ),
    ]
