# Generated by Django 4.2.3 on 2023-08-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_remove_lesson_learning_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_outline',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
