# Generated by Django 4.2.3 on 2023-08-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_quizquestion_quizresponse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together={('lesson', 'order')},
        ),
    ]
