# Generated by Django 4.2.3 on 2023-08-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_alter_quizquestion_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='correctAnswer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='wrongAnswer1',
            new_name='op1',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='wrongAnswer2',
            new_name='op2',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='op3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
