# Generated by Django 4.2.3 on 2023-08-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_student_classroom'),
        ('classroom', '0018_alter_quizquestion_op3'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonQuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
            options={
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
