# Generated by Django 4.2.3 on 2023-08-22 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0020_lessoncomments_commentmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lessonComments',
            new_name='LessonComment',
        ),
        migrations.RenameField(
            model_name='commentmessage',
            old_name='lessonComments',
            new_name='lessonComment',
        ),
    ]
