# Generated by Django 4.2.3 on 2023-08-22 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0021_rename_lessoncomments_lessoncomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmessage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
