# Generated by Django 4.2.3 on 2023-08-22 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0022_alter_commentmessage_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmessage',
            name='lessonComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classroom.lessoncomment'),
        ),
    ]
