# Generated by Django 4.2.3 on 2023-08-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0023_alter_commentmessage_lessoncomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='commentmessage',
            name='lessonComment',
        ),
        migrations.AddField(
            model_name='commentmessage',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.lesson'),
        ),
        migrations.DeleteModel(
            name='LessonComment',
        ),
    ]
