# Generated by Django 4.2.3 on 2023-08-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0024_alter_commentmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmessage',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.lesson'),
        ),
    ]
