# Generated by Django 4.2.3 on 2023-07-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='balance',
            new_name='cash',
        ),
        migrations.AddField(
            model_name='student',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
