# Generated by Django 4.2.3 on 2023-08-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordTimeSet',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
