# Generated by Django 4.2.3 on 2023-08-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_passwordtimeset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passwordTimeSet',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
