# Generated by Django 4.2.3 on 2023-08-24 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_passwordtimeset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passwordTimeSet',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
